const reflections = [
  {
    title: "The model learned my formula, not medicine",
    text: "This is the honest limitation, and it is the thing I understood only after the accuracy score came back high. The outcomes in the dataset were generated by a weighted formula I wrote. A high score means the forest successfully recovered that formula from the data, which validates the pipeline and proves nothing about transplants. Real validation needs real outcomes.",
  },
  {
    title: "A simulation inherits every assumption you put in it",
    text: "The weights came from published research, but choosing 0.30 for donor age rather than 0.25 was my call, and the model cannot see past it. The age range of 18 to 120 is wider than any real donor pool. Building the data taught me that the assumptions do not disappear once they are in code, they just become harder to notice.",
  },
  {
    title: "Accuracy is the least interesting number",
    text: "I started out treating the accuracy score as the result. By the end it was the confusion matrix that told me something, because it separates the two ways of being wrong. In a domain where one error means a failed transplant and the other means a viable organ passed over, an average across both is the wrong summary.",
  },
  {
    title: "Where the code stops and judgment starts",
    text: "The point of a tool like this would be to give a transplant team one more input, not to make a decision for them. Allocation involves urgency, waiting time, and circumstances no feature column captures. Getting clear on what a model is not for turned out to be as much of the work as building it.",
  },
];

export default function Chapter5() {
  return (
    <section className="bg-slate-50 px-8 py-32">
      <div className="mx-auto max-w-6xl">

        {/* Header */}

        <div className="text-center">
          <p className="text-sm font-semibold uppercase tracking-[0.3em] text-blue-600">
            Reflection
          </p>

          <h2 className="mt-4 text-5xl font-bold text-slate-900">
            What the Model Can and Cannot Say
          </h2>

          <p className="mx-auto mt-8 max-w-3xl text-lg leading-9 text-slate-600">
            The most valuable part of this project was learning to describe its
            limits precisely.
          </p>
        </div>

        {/* Reflection Cards */}

        <div className="mt-24 space-y-10">
          {reflections.map((item) => (
            <div
              key={item.title}
              className="rounded-3xl border border-slate-200 bg-white p-10 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-lg"
            >
              <h3 className="text-2xl font-semibold text-slate-900">
                {item.title}
              </h3>

              <p className="mt-6 leading-8 text-slate-600">
                {item.text}
              </p>
            </div>
          ))}
        </div>

        {/* What comes next */}

        <div className="mt-24 rounded-3xl border border-slate-200 bg-white p-12 shadow-sm">
          <p className="text-sm font-semibold uppercase tracking-widest text-blue-600">
            What I Would Do Next
          </p>

          <h3 className="mt-4 text-3xl font-bold text-slate-900">
            The version of this that would mean something.
          </h3>

          <ul className="mt-8 space-y-4 text-lg leading-8 text-slate-600">
            <li>
              • Train on a de-identified registry dataset, so the outcomes come
              from transplants that actually happened.
            </li>
            <li>
              • Check calibration, not just accuracy. A model that says 0.7
              should be right about 70 percent of the time it says that.
            </li>
            <li>
              • Examine the predictions across demographic groups, because a
              model that is accurate on average can still be worse for some
              patients than others.
            </li>
            <li>
              • Report feature importances against the medical literature, as a
              way of checking whether the model learned something reasonable or
              something merely convenient.
            </li>
          </ul>
        </div>

        {/* Acknowledgment */}

        <div className="mt-16 rounded-3xl bg-slate-900 p-12 text-center">
          <h3 className="text-3xl font-bold text-white">
            Looking Forward
          </h3>

          <p className="mx-auto mt-8 max-w-4xl text-lg leading-9 text-slate-300">
            This project sits where two of my interests meet: artificial
            intelligence and biomedical engineering. It was written for CSC 280
            with Prof. Sandra Wiktor, and it is the reason I want to keep
            working on machine learning applied to medicine, where being
            careful about what a model claims matters as much as building it.
          </p>
        </div>

      </div>
    </section>
  );
}
